import React from 'react';
import Row from '../src/Row.jsx';
import Column from '../src/Column.jsx';
import Item from '../src/Item.jsx';
// import Readme from '../README.md';

export default class App extends React.Component {

  constructor(props){
    super(props);
  }

  documentation() {
    return { __html : 'Body'};
  }

  render() {
    return (
      <Column justify="center">
        <Row className="header" align="center">
          <span className="watcher"></span>
          <Item size="66%" small="hide" className="hero">
            <h1><span className="type"></span><span className="cursor">|</span></h1>
            <h2></h2>
          </Item>
          <Item small="100%" className="repo-link">
            <a href="https://github.com/111StudioKK/react-plan" className="button"><span><small>View project on</small> GitHub</span></a>
          </Item>
        </Row>
        <Row className="body">
          <Item size={3}>
            <div dangerouslySetInnerHTML={this.documentation()}></div>
          </Item>
          <Item className="menu" size={1} align="stretch" small="hide" medium="hide" >
            <div>
              <ul>
                <li><a href="#">Documentation</a></li>
                <li><a href="#demonstration">Demonstration</a></li>
              </ul>
              <img src={require('./images/download-button.png')} alt=""/>
              <img src={require('./images/download-button.png')} alt=""/>
               <p className="repo-owner"><a href="https://github.com/111StudioKK/react-plan">react-plan</a> is maintained by <a href="https://github.com/111StudioKK">111StudioKK</a>.</p>
              <p>This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using the Architect theme by <a href="https://twitter.com/jasonlong">Jason Long</a>.</p>
            </div>
          </Item>
        </Row>
     </Column>
    );
  }
}